version: '3.8'
services:
  postgres_db_hexarq:
    image: postgres:latest
    container_name: HexArq-DB-dev
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todo_db
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres

  application_hexarq:
    environment:
      - POSTGRES_HOST=postgres_db_hexarq
      - APP_ENV=development
      - APP_PORT=3003
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DBNAME=todo_db
      - POSTGRES_PORT=5432
    build:
      context: ../../
      dockerfile: ./scripts/docker/local/Dockerfile
    container_name: HexArq-App-dev
    restart: always
    ports:
      - 3003:3003
    depends_on:
      postgres_db_hexarq:
                  condition: service_healthy
