version: '3.8'
services:
  postgres_db_local:
    image: postgres:latest
    container_name: HexArq-DB
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todo_db
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres